Repository coze-dev/coze-java, pull requests merged in 2024-12, with the labels that each got.

#4 chore: Update CI config with matrix Java versions and revise CONTRIBUTING.md
  .github/workflows/ci.yml
  CONTRIBUTING.md
Labels: chore

#7 feat: Enhance SDK with new features, improve documentation, and transition to Maven
  .coderabbit.yaml
  .github/release-drafter.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .gitignore
  CONTRIBUTING.md
  README.md
  api/build.gradle
  api/pom.xml
  api/src/main/java/com/coze/openapi/client/connversations/message/CreateMessageReq.java
  api/src/main/java/com/coze/openapi/client/connversations/message/UpdateMessageReq.java
  api/src/main/java/com/coze/openapi/client/dataset/document/UpdateDocumentReq.java
  api/src/main/java/com/coze/openapi/service/auth/JWTOAuthClient.java
  api/src/main/java/com/coze/openapi/service/auth/OAuthClient.java
  api/src/main/java/com/coze/openapi/service/service/CozeAPI.java
  api/src/main/java/com/coze/openapi/service/service/chat/ChatService.java
  build.gradle
  example/build.gradle
  example/pom.xml
  example/src/main/java/example/chat/SubmitToolOutputExample.java
  example/src/main/java/example/conversation/ConversationCreateExample.java
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  pom.xml
  settings.gradle
Labels: feature

#8 chore: Add configuration for release-drafter workflow
  .github/workflows/ci.yml
Labels: chore

#9 chore: Release version 0.1.2
  api/pom.xml
Labels: chore

#10 chore: Remove JaCoCo code coverage check
  pom.xml
Labels: chore

#15 fix: Rename coze-sdk to coze and release coze-api v0.1.4 with API fixes
  api/pom.xml
  api/src/main/java/com/coze/openapi/client/connversations/message/CreateMessageReq.java
  api/src/main/java/com/coze/openapi/client/connversations/message/ListMessageReq.java
  api/src/main/java/com/coze/openapi/client/workspace/model/Workspace.java
  example/pom.xml
  pom.xml
Labels: bug

#16 docs: Update chat examples
  example/src/main/java/example/conversation/ConversationCreateExample.java
Labels: chore

#17 fix: Require app_id for workflow execution within app context
  api/src/main/java/com/coze/openapi/client/workflows/run/RunWorkflowReq.java
Labels: bug

#18 docs: Update Maven badge in README
  README.md
Labels: chore

#19 chore: Release version 0.1.5
  api/pom.xml
  pom.xml
Labels: chore

#20 fix: Fix User Agent reporting
  api/pom.xml
  api/src/main/java/com/coze/openapi/service/utils/UserAgentInterceptor.java
  api/src/test/java/com/coze/openapi/service/utils/UserAgentInterceptorTest.java
  pom.xml
Labels: bug
